ready for testing script

diff --git a/.github/workflows/FK3.yml b/.github/workflows/FK3.yml
--- a/.github/workflows/FK3.yml
+++ b/.github/workflows/FK3.yml
@@ -10,6 +10,10 @@ on:
         description: Log error handling based on test result
         required: true
         default: false
+        type: choice
+        options:
+          - true
+          - false
 
 
 env:
@@ -42,6 +46,8 @@ jobs:
     name: Run a pytest on API retrieval and data processing
     runs-on: ubuntu-latest
     needs: environment_check
+    outputs:
+      result: ${{ steps.result.outputs.result }}
 
     steps:
       - name: Checkout repository
@@ -59,14 +65,24 @@ jobs:
 
       - name: Run tests
         run: |
-          pytest test_api.py test_process_smhi_data.py > error-output.log 2>&1
+          pytest test_api.py test_process_smhi_data.py > error-output.log 2>&1 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+
+      - name: Result output
+        id: result
+        run: |
+          if [ "${TEST_FAILED}" = "true" ]; then
+            echo "result=failure" >> $GITHUB_OUTPUT
+          else
+            echo "result=success" >> $GITHUB_OUTPUT
+          fi
 
 
   logging_errors:
     name: Upload error logs if the tests fail
     runs-on: ubuntu-latest
     needs: tests
-    if: ${{ github.event.inputs.logging_errors == 'true' && needs.tests.result == 'failure' }}
+    if: ${{ github.event.inputs.logging_errors == 'true' && needs.tests.outputs.result == 'failure' }}
+    
 
     steps:
       - name: Checkout repository
@@ -84,7 +100,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: tests
 
-    if: needs.tests.result == 'success'
+    if: needs.tests.outputs.result == 'success'
     steps:
       - name : Checkout repository
         uses: actions/checkout@v4
